#ifndef _FREELANCER_H_
#define _FREELANCER_H_

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define INI_READER_CONSTRUCTOR_IMPORT_ADDR 0x5C605C
#define INI_READER_DESTRUCTOR_IMPORT_ADDR 0x5C6048
#define INI_READER_OPEN_IMPORT_ADDR 0x5C6058
#define INI_READER_READ_HEADER_IMPORT_ADDR 0x5C6054
#define INI_READER_IS_HEADER_IMPORT_ADDR 0x5C6050
#define INI_READER_READ_VALUE_IMPORT_ADDR 0x5C669C
#define INI_READER_IS_VALUE_IMPORT_ADDR 0x5C6CF4
#define INI_READER_GET_VALUE_BOOL_IMPORT_ADDR 0x5C6034
#define INI_READER_GET_VALUE_FLOAT_IMPORT_ADDR 0x5C6CFC
#define INI_READER_CLOSE_IMPORT_ADDR 0x5C6400

#define SHIP_PREVIEW_SCROLL_ADDR ( (PDWORD) 0x5E4C14 )

struct ShipTrader3DShip
{
    BYTE x00[0x3EC];
    float zoomLevel;
};

#endif
